#!/bin/sh

MUTED="$(pacmd list-sinks|grep -A 15 '* index'|awk '/muted:/{ print $2 }')"

if [ $MUTED == "no" ]; then
  echo "$(pactl list sinks | grep -E '^\s+Volume:' | head -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')%"
else
  echo "MUTED"
fi

