# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "uas" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/66773c39-ea86-4b86-ae8b-31a4e56bf46b";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0B7B-5F96";
      fsType = "vfat";
    };

  fileSystems."/mnt/data" =
    { device = "/dev/disk/by-uuid/8691d951-a1f4-4702-a947-e91e6afc4614";
      fsType = "ext4";
    };

  fileSystems."/mnt/enc_data_drive" =
    { device = "/dev/disk/by-uuid/af7977f8-c99e-4b48-8a25-dc716233bfd5";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."enc_data_drive".device = "/dev/disk/by-uuid/2123e639-909b-44ac-ac4a-6c896746d33f";

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault false;
  networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  networking.interfaces.wlan0.useDHCP = lib.mkDefault true;
  # networking.interfaces.podman0.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth0.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth1.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth10.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth2.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth3.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth4.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth5.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth6.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth7.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth8.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth9.useDHCP = lib.mkDefault true;
  # networking.interfaces.wg-mullvad.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
