#!/bin/sh

# File preview handler for lf.

set -C -f
IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}"

image() {
  chafa "$6"
}

case "$(file --dereference --brief --mime-type -- "$1")" in
	image/avif) CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
		[ ! -f "$CACHE" ] && convert "$1" "$CACHE.jpg"
		image "$CACHE.jpg" "$2" "$3" "$4" "$5" "$1" ;;
	image/*) image "$1" "$2" "$3" "$4" "$5" "$1" ;;
	text/html) lynx -width="$4" -display_charset=utf-8 -dump "$1" ;;
	text/troff) man ./ "$1" | col -b ;;
	text/* | */xml | application/json) bat --terminal-width "$(($4-2))" -f "$1" ;;
	audio/* | application/octet-stream) mediainfo "$1" || exit 1 ;;
	video/* ) mediainfo $1 || exit 1 ;;
	application/*zip) atool --list -- "$1" ;;
	*opendocument*) odt2txt "$1" ;;
	application/pgp-encrypted) gpg -d -- "$1" ;;
  *) echo $(file $1 | awk '{print substr($0, index($0,$2))}') ;;
esac
exit 1
