{ config, pkgs, opts, secrets, ... }:
let
  mkPort = port_str: if builtins.isString port_str then pkgs.lib.strings.toInt port_str else port_str;
in
{
  networking.firewall = {
    enable = true;
    allowPing = false;
    allowedTCPPorts = builtins.map mkPort (with opts.ports;
      [
        actual-app
        adguard_dns
        adguard_web
        archivebox
        aria_rpc
        aria_web
        audiobookshelf
        autobrr
        baikal
        bazarr
        cloudbeaver
        cockpit
        container-registry-server
        container-registry-web
        docuseal
        filebrowser
        firefly_app
        firefly_db
        flaresolverr
        freshrss
        ftp
        gitea_db
        gitea_http
        gitea_ssh
        gotify
        grafana
        homebox
        homer
        https
        huginn-app
        huginn-db
        icecast
        jackett
        jellyfin
        jellyseer
        joplin-app
        joplin-db
        kavita
        lidarr
        linkding
        memos
        metube
        navidrome
        netdata
        nextcloud-app
        nextcloud-http
        nextcloud-https
        nginx-proxy-manager-app
        nginx-proxy-manager-http
        nginx-proxy-manager-https
        ntfy
        olivetin
        ollama-api
        ollama-web
        openbooks
        paperless-app
        paperless-db
        paperless-redis
        photoprism_app
        photoprism_db
        plex
        podgrab
        portrainer_misc
        portrainer_web
        portrainer_web_secure
        prometheus_app
        prometheus_node
        prometheus_zfs
        prowlarr
        qbittorrent-p2p
        qbittorrent-web
        radarr
        readarr
        rss-bridge
        searxng
        sonarr
        ssh
        taskchampion
        tubearchivist
        tubearchivist-redis
        uptime-kuma
        vaultwarden
      ]);
    allowedUDPPorts = builtins.map mkPort (with opts.ports;
      [
        adguard_dns
        audiobookshelf
        container-registry-server
        ftp
        gitea_ssh
        gotify
        jellyfin
        qbittorrent-p2p
        ssh
      ]);
  };
}
