#!/bin/sh

wallpapersloc="$HOME/Pictures/wallpapers/"

while read -r file; do
	case "$1" in
		# Copy to clipboard
		"y") printf "%s" "$file" | tr -d '\n' | xclip -selection clipboard && notify-send "$file copied to clipboard" & ;;
		# Delete the file
		"d") [ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted" ;;
		# Delete the file without confirmation
		"D") rm -f "$file" && notify-send "$file deleted" ;;
		# Show file information
		"i") notify-send "File information" "$(mediainfo "$file")" ;;
		# Rotate the image permanently
		"r") if type convert > /dev/null 2>&1; then convert -rotate 90 "$file" "$file"; else notify-send "Imagemagick is not installed!"; fi ;;
		"R") if type convert > /dev/null 2>&1; then convert -rotate -90 "$file" "$file"; else notify-send "Imagemagick is not installed!"; fi ;;
		# Mirror the image horizontally
		"m") if type convert > /dev/null 2>&1; then convert -flop "$file" "$file"; else notify-send "Imagemagick is not installed!"; fi ;;
		# Open the file in GIMP
		"e") if type gimp > /dev/null 2>&1; then setsid -f gimp "$file"; else notify-send "Gimp is not installed!"; fi ;;
		# Set the file as wallpaper
		"w") feh --bg-scale "$file" && notify-send "$file set as wallpaper" ;;
		# Copy the file to wallpapers folder
		"W") cp -n "$file" "$wallpapersloc" && notify-send "$file copied to $wallpapersloc" || notify-send "$file already exists" ;;
    "l")
      name="$(dmenu -p "rename $file to: ")" 2> /dev/null
      if ! [ -z "$name" ]; then
        mv "$file" "$(dirname $file)/$name"
      fi
      ;;
	esac
done
