import = ["~/.config/alacritty/themes/ayu_dark.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
unfocused_hollow = false

[env]
TERM = "xterm-256color"

[font]
size   = 16
# normal = { family = "VT323", style = "Regular" }
# bold   = { family = "VT323", style = "Bold"    }
# italic = { family = "VT323", style = "Italic"  }
normal = { family = "Iosevka NF", style = "Regular" }
bold   = { family = "Iosevka NF", style = "Bold"    }
italic = { family = "Iosevka NF", style = "Italic"  }

[keyboard]
bindings = [
  { action = "ScrollPageUp",   key = "U",      mode = "~Alt", mods = "Alt" },
  { action = "ScrollPageDown", key = "D",      mode = "~Alt", mods = "Alt"  },
  { action = "ToggleViMode",   key = "Escape",                mods = "Control" },
  { action = "ToggleViMode",   key = "I",      mode = "Vi",   mods = "None" },
  { action = "ToggleViMode",   key = "Return", mode = "Vi",   mods = "None" },
]

[mouse]
bindings = [
  { action = "PasteSelection", mouse = "Middle" }
]

[scrolling]
multiplier = 5
history = 20_000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window]
decorations = "full"
opacity = 0.75
padding = { x = 5, y = 5 }
