#!/bin/sh

BATTERY_PERCENTAGE=$(upower -e | grep BAT0 | xargs -Ix upower -i x | grep percentage | awk '{print $2}')
BATTERY_STATUS=$(upower -e | grep BAT0 | xargs -Ix upower -i x | grep state | awk '{print $2}')
BATTERY_INFO="$BATTERY_PERCENTAGE $BATTERY_STATUS"

echo "BAT: $BATTERY_INFO"

exit 0
