#!/bin/sh

CPU_TEMPERATURES="$(sensors -u | grep input | grep temp | awk '{print $2}')"
AVERAGE_CPU_TEMPERATURE="$(echo $CPU_TEMPERATURES | jq -s 'add / length | round')"

ERRORS=$(echo ${AVERAGE_CPU_TEMPERATURE} | grep -ic ERROR)

if [ ${ERRORS} -eq 0 ]
then
  echo "CPU: $AVERAGE_CPU_TEMPERATUREºC"
fi
