#!/bin/sh

GPU_INFO=$(nvidia-smi -q)
PRODUCT_NAME="$(awk '/Product Name/ {print $4FS$5}' <<< $GPU_INFO)"
MEMORY_USAGE="$(awk '/Used/ {print $3;exit}' <<< "$GPU_INFO")"
TOTAL_MEMORY="$(awk '/Total/ {print $3FS$4;exit}' <<< "$GPU_INFO")"
GPU_TEMP="$(awk '/GPU Current Temp/ {print $5"°"$6;exit}' <<< "$GPU_INFO")"

echo "GFX: $PRODUCT_NAME $GPU_TEMP $MEMORY_USAGE/$TOTAL_MEMORY"

exit 0
