require("plugconf/_telescope")
require("plugconf/_lualine")
require("plugconf/_theme")
require("plugconf/_neotree")
require("plugconf/_alpha")
require("plugconf/_nvim_cmp")
require("plugconf/_lsp_zero")
