require("plugconf/_telescope")
require("plugconf/_nvim_treesitter")
require("plugconf/_lualine")
require("plugconf/_nvim_cmp")
require("plugconf/_theme")
require("plugconf/lsp")
require("plugconf/_neotree")
require("plugconf/_bufferline")
