[global]
  e2dsa  # enable file indexing and filesystem scanning
  e2ts   # enable multimedia indexing
  ansi   # enable colors in log messages
  ihead: *
  xff-src: lan
  ban-404: no
  ban-403: no
  ban-422: no
  ban-url: no
  ban-pw: no

[accounts]
  ed: wark


[/]
  /w
  accs:
    r: *
    rwmda: ed
