# TITLE: Starship Shell Prompt Configuration (Minimalist)
# AUTHOR: Sreedev Kodichath

"$schema" = 'https://starship.rs/config-schema.json'

# Don't print a new line at the start of the prompt
add_newline = false
scan_timeout = 10

format = """
$os\
$username\
$hostname\
$localip\
$directory\
$status\
$git_branch\
$custom\
$cmd_duration\
$jobs\
$character\
"""

[line_break]
disabled = true

[character]
success_symbol = "[Î»](bold green)"
error_symbol = "[Î»](bold red)"
vimcmd_symbol = "[Î»](bold purple)"

[localip]
ssh_only = true

[os]
style = "bold purple"
disabled = false

[os.symbols]
Arch = " ïŒƒ  "

[directory]
truncation_length = 2
truncate_to_repo = true
read_only = ' ðŸ”’'
read_only_style = 'bold dimmed red'
truncation_symbol = ''

[username]
format = "[â”€â”€ $user]($style)@"
style_user = "bold purple"
style_root = "bold red"
show_always = true

[git_branch]
format = "[Â» $branch]($style) "
style = "bold italic green"

[hostname]
format = "[$hostname]($style) "
style = "bold dimmed purple"
trim_at = "-"
ssh_only = false
disabled = false

[cmd_duration]
min_time = 4
show_milliseconds = true
disabled = false
style = "bold italic #87A752"

[custom.tmux]
command = "tmux ls | wc -l"
style = "bold yellow"
description = "active tmux session count"
when = "tmux ls"
disabled = false
format = "[tmux:($output)]($style) "

[jobs]
threshold = 1
symbol = "+"
style = "bold red"
