when:
  - event: [tag, manual]

matrix:
  SYSTEM:
    - x86_64-linux
    - aarch64-linux

variables:
  - &nix_image nixos/nix:latest
  - &nix_env
    NIX_CONFIG: |
      experimental-features = nix-command flakes
      accept-flake-config = true
      warn-dirty = false
    NIXPKGS_ALLOW_UNFREE: "1"

steps:
  - name: flake-check-${SYSTEM}
    image: *nix_image
    environment: *nix_env
    commands:
      - nix flake check --impure --no-build --system "${SYSTEM}"
