## All services need to be bound to 0.0.0.0 to be accessible outside the container.
log = file
loglevel = none

ipv4 = true
ipv6 = false

# Comment-out below for bandwidth limiting. Bandwidth is in KBps
# bandwidth = 256

[http]
address = 0.0.0.0
strictheaders = false

[httpproxy]
address = 0.0.0.0

[socksproxy]
enabled = false

[sam]
enabled = true
address = 0.0.0.0
port = 7656

[i2cp]
enabled = false

[upnp]
enabled = false

[reseed]
verify = true
